### ISSUE TITLE
书签

### ISSUE THREAD

**Issue by GreyElaina** [RimoChan/arxiv-translate-fix#1]
可以直接把 javascript 代码写成 `javascript:...` 的形式，并导入到浏览器的书签菜单中以供使用，如：

```
javascript:for(const i of document.querySelectorAll('math, table, cite')){i.setAttribute('translate', 'no')}
```

这样就不用装插件或者 F12 了

**Comment by GreyElaina** [comment]
[将此链接拖入浏览器书签工具栏](javascript:for(const i of document.querySelectorAll('math, table, cite')){i.setAttribute('translate', 'no')})

**Comment by RimoChan** [comment]
好！
